version: "2"

services:
  influxdb:
    image: influxdb:1.8.0
    environment:
      - INFLUX_DB=telegraf
    volumes:
      - tigstack:/var/lib/influxdb
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:1.14
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./mibs:/usr/share/snmp/mibs
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"

    links:
      - influxdb

  grafana:
    image: grafana/grafana:7.0.0
    environment: 
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - tigstack:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  tigstack:
